### ISSUE TITLE
Decode sets as MapSet?

### ISSUE THREAD

**Issue by stocks29** [ex-aws/ex_aws_dynamo#5]
Currently both string sets (`SS`) and number sets (`NS`) decode to an elixir list. In order to encode to a number set or string set, you need to use a `MapSet`. Given this, it seems like it would be more appropriate for `SS` and `NS` to decode to `MapSet` instead of a list.

I create a PR (https://github.com/ex-aws/ex_aws_dynamo/pull/4) with this new functionality and some tests in order to get the discussion going here. Interested to hear thoughts on this.

Not included in this PR, but I'm also thinking it'd be nice if, for attribute values contain an empty MapSet, the attribute itself were excluded during the encoding process. This would make sets much more natural to work with. Given the current behavior, you have to check if an attribute contains an empty MapSet and remove it, before attempting to encode in order to avoid this runtime error:

```elixir
      MapSet.size(mapset) == 0 ->
        raise "Cannot determine a proper data type for an empty MapSet"
```

**Comment by hirocaster** [comment]
Sounds good, but Incompatible changes.

**Comment by stocks29** [comment]
@hirocaster , could you please elaborate on what you mean? Are you saying the changes break semver. If this is adopted I was thinking we should bump major versions. I suppose we could look to add in some sort of compatibility mode, but I'm not sure that is worth it given that it should be easy enough to adapt code.

**Comment by hirocaster** [comment]
I think that this change should be added to the next major version. Do not need compatibility mode.

**Comment by stocks29** [comment]
Any thoughts specifically on the proposal which I did not include in this pr?

**Comment by darrenklein** [comment]
This feature has been merged to master. Thanks @stocks29 for your hard work.

**Comment by darrenklein** [comment]
https://github.com/ex-aws/ex_aws_dynamo/commit/81cc6987499debe9b4ca31564e8a915c86e660eb
